apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-app-deployment
spec:
  selector:
    matchLabels:
      app: face-app
  replicas: 2
  template:
    metadata:
      labels:
        app: face-app
    spec:
      containers:
      - name: my-face-app
        imagePullPolicy: IfNotPresent
        image: mhassan0992/face_recog_app:first
        ports:
        - containerPort: 2020

